parameters:
  "service-dir":
    default: "sdk/easm"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
  disable:
    "@azure-tools/typespec-azure-core/composition-over-inheritance": "New rule"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emit-lro-options: "none"
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/Microsoft.EasmX/{version-status}/{version}/easmx.json"
  "@azure-tools/typespec-ts":
    package-dir: "defendereasmx-rest"
    packageDetails:
      name: "@azure-rest/defender-easmx-rest"
    flavor: azure

