parameters:
  "service-dir":
    default: "sdk/apicenter"
  "dependencies":
    "additionalDirectories": []
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emit-lro-options: "none"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/azure.apicenter.dataapi.json"
  "@azure-tools/typespec-ts":
    package-dir: "azure-apicenter-rest"
    generateMetadata: true
    generateTest: true
    flavor: azure
    packageDetails:
      name: "@azure-rest/azure-apicenter-rest"
      description: "azure.ApiCenter Service"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
