parameters:
  "service-dir":
    default: "sdk/mongocluster"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-ts":
    azureSdkForJs: true
    isModularLibrary: true
    generateMetadata: true
    hierarchyClient: true
    experimentalExtensibleEnums: true
    package-name: "@azure/arm-mongocluster"
    flavor: "azure"
    package-dir: "arm-mongocluster"
    packageDetails:
      name: "@azure/arm-mongocluster"
      description: "DocumentDB MongoCluster Service"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
