emit:
  - "@azure-tools/typespec-autorest"
parameters:
  "service-dir":
    default: "sdk/sphere"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/azuresphere.json"
    examples-directory: "{project-root}/examples"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-sphere"
    flavor: "azure"
    namespace: "com.azure.resourcemanager.sphere"
    service-name: "Azure Sphere"
    examples-directory: "examples"
  "@azure-tools/cadl-python":
    "basic-setup-py": true
    "package-version": 3.0.0b6
    "package-name": azure-sphere
  "@azure-tools/cadl-csharp":
    save-inputs: false
    clear-output-folder: true
    namespace: Azure.Sphere
    model-namespace: false
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
