parameters:
  "service-dir":
    "default": "sdk/documentintelligence"

emit:
  - "@azure-tools/typespec-autorest"
  # - "@azure-tools/typespec-csharp",
  # - "@azure-tools/typespec-python",
  # - "@azure-tools/typespec-ts"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emit-lro-options: "none"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "examples"
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json"
  "@azure-tools/typespec-python":
    package-pprint-name: "Azure AI Document Intelligence"
    package-dir: "azure-ai-documentintelligence"
    package-name: "{package-dir}"
    package-version: 1.0.0b2
    flavor: azure
