parameters:
  "service-dir":
    default: "sdk/edgezones"
emit:
  - "@azure-tools/typespec-ts"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    examples-directory: "examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/edgezones.json"
  "@azure-tools/typespec-python":
    package-dir: "azure-mgmt-edgezones"
    package-name: "{package-dir}"
    generate-test: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    package-dir: "azure-resourcemanager-edgezones"
    flavor: "azure"
    namespace: "com.azure.resourcemanager.edgezones"
    service-name: "Edge Zones"
    examples-directory: "examples"
  "@azure-tools/typespec-ts":
    azureSdkForJs: true
    isModularLibrary: true
    generateMetadata: true
    hierarchyClient: false
    experimentalExtensibleEnums: true
    enableOperationGroup: true
    package-name: "@azure/arm-edgezones"
    package-dir: "arm-edgezones"
    emitter-output-dir: "{project-root}/sdk/edgezones/arm-edgezones"
    flavor: "azure"
    packageDetails:
      name: "@azure/arm-edgezones"
      description: "Microsoft Edgezones Service"
