emit:
  - "@azure-tools/typespec-ts"
parameters:
  "service-dir":
    default: "sdk/deviceregistry"
options:
  "@azure-tools/typespec-autorest":
    isModularLibrary: true
    "emitter-output-dir": "{project-root}/generated/typespec-ts"
    packageDetails:
      name: "@msinternal/test-js-sdk-release-tool"
      description: "OpenAI"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
