parameters:
  - name: SpecRepoUrl
    type: string
    default: 'https://github.com/Azure/azure-rest-api-specs'
  - name: SpecRepoBranch
    type: string
    default: 'main'
  - name: SpecRepoCommit
    type: string
    default: 'HEAD'
  - name: SdkRepoUrl
    type: string
    default: 'https://github.com/Azure/azure-sdk-for-net'
  - name: SdkRepoBranch
    type: string
    default: 'main'
  - name: ConfigType
    type: string
    values:
      - 'TypeSpec'
      - 'AutoRest'
    default: 'TypeSpec'
    displayName: 'Configuration Type'
  - name: TspConfigPath
    type: string
    default: 'specification/contosowidgetmanager/Contoso.Management/tspconfig.yaml'
    displayName: 'Path to TypeSpec Configuration file'
  - name: ReadmePath
    type: string
    default: 'specification/contosowidgetmanager/data-plane/readme.md'
    displayName: 'Path to AutoRest Configuration file (for OpenAPI)'
  - name: ApiVersion
    type: string
    default: 'not-specified'
    displayName: 'API Version of Spec to be used for SDK Generation'
  - name: SkipPullRequestCreation
    type: boolean
    default: false
    displayName: 'Skip Pull Request Creation'

trigger:
  branches:
    include:
      - user/raych1/pipeline-sdk-auto
pr:
  branches:
    include:
      - user/raych1/pipeline-sdk-auto
steps:
  - template: /eng/common/pipelines/templates/jobs/sdk-generation.yml
    parameters:
      SpecRepoUrl: ${{ parameters.SpecRepoUrl }}
      SpecRepoBranch: ${{ parameters.SpecRepoBranch }}
      SpecRepoCommit: ${{ parameters.SpecRepoCommit }}
      SdkRepoUrl: ${{ parameters.SdkRepoUrl }}
      SdkRepoBranch: ${{ parameters.SdkRepoBranch }}
      ConfigType: ${{ parameters.ConfigType }}
      TspConfigPath: ${{ parameters.TspConfigPath }}
      ReadmePath: ${{ parameters.ReadmePath }}
      ApiVersion: ${{ parameters.ApiVersion }}
      SkipPullRequestCreation: ${{ parameters.SkipPullRequestCreation }}
